name: Release

on:
  push:
    tags:
    - "v**"

jobs:

  release-github:
    name: Create Github Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download Plugin
        run: wget "https://github.com/mahaloz/binsync-ghidra-plugin/releases/latest/download/binsync-ghidra-plugin.zip"
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          artifacts: "binsync-ghidra-plugin.zip"
