name: Release

on:
  push:
    tags:
    - "v**"

jobs:

  release-github:
    name: Create Github Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          # bodyFile: "body.md"
          generateReleaseNotes: true


